// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAreYBnY1-cDbzeixNgqWOLD5IrFeQE6to',
    appId: '1:588650915805:web:03a5c5aaa034515bf0b834',
    messagingSenderId: '588650915805',
    projectId: 'coffee-shop-app-9c07f',
    authDomain: 'coffee-shop-app-9c07f.firebaseapp.com',
    storageBucket: 'coffee-shop-app-9c07f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHtnj3Y8k-UvxtwKeAwb0kW0sIJzRqXhw',
    appId: '1:588650915805:android:43e0134b77f51cc1f0b834',
    messagingSenderId: '588650915805',
    projectId: 'coffee-shop-app-9c07f',
    storageBucket: 'coffee-shop-app-9c07f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIEuuAC5FZK6Nc1z-M7SUMnsts4e9TrCw',
    appId: '1:588650915805:ios:63a0d79876eadb12f0b834',
    messagingSenderId: '588650915805',
    projectId: 'coffee-shop-app-9c07f',
    storageBucket: 'coffee-shop-app-9c07f.appspot.com',
    iosBundleId: 'com.example.coffeeShopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIEuuAC5FZK6Nc1z-M7SUMnsts4e9TrCw',
    appId: '1:588650915805:ios:14e1498c5469bda8f0b834',
    messagingSenderId: '588650915805',
    projectId: 'coffee-shop-app-9c07f',
    storageBucket: 'coffee-shop-app-9c07f.appspot.com',
    iosBundleId: 'com.example.coffeeShopApp.RunnerTests',
  );
}
